"""Shared rate-limit and refresh constants."""

from __future__ import annotations

LIVE_REFRESH_DEFAULT_SECONDS = 5
LIVE_REFRESH_MIN_SECONDS = 3
LIVE_REFRESH_MAX_SECONDS = 300

ENRICHMENT_REQUESTS_PER_MINUTE = 30
ENRICHMENT_MAX_BURST = 10
ENRICHMENT_SUCCESS_TTL_SECONDS = 43_200  # 12 hours
ENRICHMENT_FAILURE_TTL_SECONDS = 1_800  # 30 minutes

GEOCODING_MIN_INTERVAL_SECONDS = 1.0
